### ISSUE TITLE
Deploy Shib MDQ server on K8S

### ISSUE THREAD

**Issue by federicaagostini** [eosc-kc/keycloak#106]
Deploy an mdq-server on the k8s cluster@CNAF configured to serve three different metadata aggregates:
* EduGAIN entities
* IDEM entities (https://www.idem.garr.it/)
* test entities (i.e., test-idp.cloud.cnaf.infn.it and a cloud of test idps configured on kc-test.cloud.cnaf.infn.it)

The mdq server should be deployed to answer on https at 
https://mdq-test.cloud.cnaf.infn.it

---

IDEM metadata help page:
https://wiki.idem.garr.it/wiki/Metadata

mdq-server source code:
https://github.com/iay/mdq-server

**Comment by federicaagostini** [comment]
## Progress report

The MDQ server configurations adapted for our use case live in the following eosc-kc GitHub repo: 
https://github.com/eosc-kc/mdq-server-docker/tree/idem/idem (branch `idem`) 

A docker image for the MDQ server is built on top of the `ianayoung/mdq-server` image;
use the [build](https://github.com/eosc-kc/mdq-server-docker/blob/idem/idem/build) script to build the image and the [docker-compose](https://github.com/eosc-kc/mdq-server-docker/blob/idem/idem/docker-compose.yml) file to run the service locally.

The MDQ server now loads metadata from IDEM/EduGain + test-entities (kc-test.cloud.cnaf.infn.it and test-idp.cloud.cnaf.infn.it).
For IDEM/EduGain aggregate it basically checks the "valid until" field, checks the IDEM signature, filters out the service providers and signs the new metadata; for test entities it just apply the signing phase. 

A simple shell script ([mdq_url.sh](https://github.com/eosc-kc/mdq-server-docker/blob/idem/idem/scripts/mdq_url.sh)) illustrates the client side of the MDQ server:
```
# the base URL of the MDQ server
$ export MDQ_BASE_URL=localhost:8080
 
# an entityID for testing
$ entityID=https://idp.infn.it/saml2/idp/metadata.php
 
# compute the MDQ protocol URL
$ mdq_url.sh $entityID
localhost:8080/entities/https%3A%2F%2Fidp.infn.it%2Fsaml2%2Fidp%2Fmetadata.php
 
# retrieve a signed entity descriptor
$ curl $(mdq_url.sh $entityID)
```

The MDQ server also saves:

- a `discofeed.json` file with the filtered aggregate obtained from IDEM/EduGain metadata
- filtered and signed xml metadata files, one for each entityID (both from IDEM/EduGain and test entities)

in a local volume shared with the container, at `mdq-server-docker/idem/shared-volume`.
Each xml file is named as a function of the entity's entityID attribute; we can get it from this simple [script](https://github.com/eosc-kc/mdq-server-docker/blob/idem/idem/scripts/get-metadata.sh) (default entityID is set to the INFN one).

## Todo list

- [ ] save an unique metadata aggragate in an xml file
- [ ] update README
- [ ] push mdq-server docker image on DockerHub
- [ ] deploy mdq-server on the k8s cluster@CNAF

**Comment by federicaagostini** [comment]
The MDQ server now also saves a filtered and signed metadata aggregate obtained from IDEM/EduGain metadata; it is located in  `mdq-server-docker/idem/shared-volume/filtered-aggregate.xml`.

Moreover, we can customize the metadata source refresh interval in [application.properties](https://github.com/eosc-kc/mdq-server-docker/blob/idem/idem/resources/config/application.properties#L28) (set to 6h)

**Comment by federicaagostini** [comment]
The service is now ready in production and responds to
* https://mdq-test.cloud.cnaf.infn.it/entities it loads all entities
* https://mdq-test.cloud.cnaf.infn.it/entities/{URL_encoded_entityID}

**Comment by ctriant** [comment]
Hello!
Is there the possibility to change the metadata sources on the config.xml without the need to restart the server?
